# Generated by cucumber-sinatra. (2015-05-04 12:40:50 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'toDoListServer')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ToDoListServer

class ToDoListServerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ToDoListServerWorld.new
end
